In [5]:
import pandas as pd

# **Dataset 1 — Appliances Energy Prediction (UCI)**

Fonte: https://archive.ics.uci.edu/dataset/374/appliances+energy+prediction

Situação:

A empresa de eficiência energética está analisando o comportamento de uma residência de baixo consumo. A equipe deseja identificar períodos de consumo elevado dos eletrodomésticos e observar quais condições de temperatura e umidade estavam presentes nesses momentos.

1.	Carregue a amostra no Pandas e apresente head(), shape, info() e describe().

In [81]:
df1 = pd.read_csv('/content/energydata_SAMPLE_01.csv')

In [82]:
df1.head()

   Appliances  lights       T1     RH_1       T2     RH_2       T3     RH_3
0          40       0  20.8900  35.4000  17.7600  39.1633  20.2900  36.9000
1          90      10  21.8900  53.1000  21.2900  45.3600  21.6333  49.2267
2          50       0  21.3900  35.5000  17.6333  40.5300  21.6667  35.2000
3          50       0  21.3900  41.0333  23.8900  34.8400  22.0333  36.9333
4          70       0  19.9633  35.1267  16.4633  40.1267  20.0000  36.4000

In [83]:
print(f'O dataset possui {df1.shape[0]} linhas e {df1.shape[1]} colunas')

O dataset possui 1974 linhas e 8 colunas

In [84]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1974 entries, 0 to 1973
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Appliances  1974 non-null   int64
 1   lights      1974 non-null   int64
 2   T1          1974 non-null   float64
 3   RH_1        1974 non-null   float64
 4   T2          1974 non-null   float64
 5   RH_2        1974 non-null   float64
 6   T3          1974 non-null   float64
 7   RH_3        1974 non-null   float64
dtypes: float64(6), int64(2)
memory usage: 123.5 KB

In [85]:
df1.describe()

,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3
count,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000
mean,93.044580,3.839919,21.664703,40.219193,20.293635,40.411386,22.231615,39.209733
std,93.826149,7.937076,1.574883,3.971923,2.126958,4.037686,1.957275,3.288818
min,20.000000,0.000000,16.790000,27.733300,16.100000,24.063300,17.200000,30.133300
25%,50.000000,0.000000,20.700000,37.205825,18.790000,37.760000,20.700000,36.900000
50%,60.000000,0.000000,21.600000,39.590000,20.000000,40.433300,22.100000,38.433300
75%,100.000000,0.000000,22.600000,42.991675,21.500000,43.228325,23.290000,41.741250
max,770.000000,50.000000,26.260000,57.496700,28.917500,56.026700,29.198600,49.226700

2.	Renomeie Appliances para Consumo_Eletrodomesticos e simplifique o nome de pelo menos três atributos ambientais.

In [86]:
df1.columns

Index(['Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3'], dtype='object')

In [87]:
df1.rename(columns={'Appliances':'Consumo_Eletrodomesticos',
                    'T1':'Temperatura_Setor_1',
                    'RH_1':'Umidade_Setor_1',
                    'T2':'Temperatura_Setor_2',
                    'RH_2':'Umidade_Setor_2',
                    'T3':'Temperatura_Setor_3',
                    'RH_3':'Umidade_Setor_3',
                    }, inplace=True)

3.	Determine o maior consumo de eletrodomésticos registrado na amostra.

In [88]:
consumoMax_df1 = df1['Consumo_Eletrodomesticos'].max()

consumoMax_df1

770

4.	Calcule um limiar correspondente a 70% do valor máximo e crie um DataFrame contendo somente os registros acima desse limite

In [89]:
limiarConsumo_df1 = consumoMax_df1 * 0.70

limiarConsumo_df1

539.0

In [90]:
df1_altoConsumo = df1[df1['Consumo_Eletrodomesticos'] > limiarConsumo_df1]

df1_altoConsumo.head()

,Consumo_Eletrodomesticos,lights,Temperatura_Setor_1,Umidade_Setor_1,Temperatura_Setor_2,Umidade_Setor_2,Temperatura_Setor_3,Umidade_Setor_3
352,620,0,24.3900,44.3333,25.3700,37.7360,26.7300,38.8633
427,650,0,20.8900,36.7000,18.2900,39.6633,21.2000,36.0000
453,560,30,21.3567,36.0900,19.5667,37.1633,21.6333,35.0300
616,570,10,24.8900,32.6667,23.5600,31.1400,23.6000,30.8233
696,590,30,19.8567,47.6633,18.7000,34.1000,18.4267,37.8333

5.	Conte os registros selecionados e calcule qual percentual da amostra eles representam.

In [91]:
nRegistrosAltoConsumo_df1 = len(df1_altoConsumo)
totalRegistros_df1 = len(df1)

percentualAltoConsumo_df1 = (nRegistrosAltoConsumo_df1 / totalRegistros_df1) * 100

print(f"Número de registros com consumo acima do limiar: {nRegistrosAltoConsumo_df1}")
print(f"Total de registros da amostra: {totalRegistros_df1}")
print(f"Percentual de registros com consumo acima do limiar da amostra: {percentualAltoConsumo_df1:.2f}%")

Número de registros com consumo acima do limiar: 22
Total de registros da amostra: 1974
Percentual de registros com consumo acima do limiar da amostra: 1.11%

6.	Calcule a temperatura média de T1 e crie outro DataFrame contendo simultaneamente consumo acima de 70% do máximo e temperatura acima da média.

In [92]:
media_t1_df1 = df1['Temperatura_Setor_1'].mean()

df1_altoConsumo_t1 = df1_altoConsumo[df1_altoConsumo['Temperatura_Setor_1'] > media_t1_df1]

df1_altoConsumo_t1.head()

,Consumo_Eletrodomesticos,lights,Temperatura_Setor_1,Umidade_Setor_1,Temperatura_Setor_2,Umidade_Setor_2,Temperatura_Setor_3,Umidade_Setor_3
352,620,0,24.3900,44.3333,25.3700,37.7360,26.73,38.8633
616,570,10,24.8900,32.6667,23.5600,31.1400,23.60,30.8233
916,750,30,22.4300,43.0000,21.9267,40.1333,21.23,42.5967
993,690,10,22.5333,45.0267,22.0667,39.7900,22.39,41.9300
1182,600,20,24.8900,48.1333,28.9175,37.9475,27.10,42.4400

7.	Compare os dois DataFrames e explique o efeito da inclusão da temperatura como segundo critério.

In [93]:
print(f'O dataset df_alto_consumo possui {df1_altoConsumo.shape[0]} linhas e {df1_altoConsumo.shape[1]} colunas')
print(f'O dataset df_alto_consumo_t1 possui {df1_altoConsumo_t1.shape[0]} linhas e {df1_altoConsumo_t1.shape[1]} colunas')

O dataset df_alto_consumo possui 22 linhas e 8 colunas
O dataset df_alto_consumo_t1 possui 8 linhas e 8 colunas

Ao incluir a temperatura acima da média de T1 como segundo critério, o número de registros no DataFrame `df1_altoConsumo_t1` diminui em comparação com `df1_altoConsumo`. Isso ocorre porque estamos aplicando uma condição mais restritiva, filtrando apenas os casos de alto consumo que também ocorrem quando a temperatura no setor 1 (T1) está acima de sua média.

Isso demonstra que nem todos os eventos de alto consumo estão associados a temperaturas elevadas no Setor 1. A inclusão desse critério nos permite focar em um subconjunto de eventos de alto consumo que compartilham uma característica ambiental específica, o que pode ser útil para entender padrões de consumo em diferentes condições.

# **Dataset 2 — Steel Industry Energy Consumption (UCI)**

Fonte: https://archive.ics.uci.edu/dataset/851/steel+industry+energy+consumption

Situação:

A equipe de gestão de energia de uma indústria siderúrgica deseja localizar situações de consumo elevado e verificar se esses períodos coincidem com condições de carga elevada ou valores menos favoráveis de fator de potência.

1. Carregue a amostra e renomeie Usage_kWh para Consumo_kWh, simplificando também os nomes dos atributos de fator de potência.

In [94]:
df2 = pd.read_csv('/content/Steel_industry_data_SAMPLE_01.csv')

In [95]:
df2.columns

Index(['date', 'Usage_kWh', 'Lagging_Current_Reactive.Power_kVarh',
       'Leading_Current_Reactive_Power_kVarh', 'Lagging_Current_Power_Factor',
       'Leading_Current_Power_Factor', 'WeekStatus', 'Day_of_week',
       'Load_Type'],
      dtype='object')

In [96]:
df2.rename(columns={'Usage_kWh': 'Consumo_kWh',
                    'Lagging_Current_Power_Factor': 'Fator_Potencia_Atrasado',
                    'Leading_Current_Power_Factor': 'Fator_Potencia_Adiantado'
                    }, inplace=True)

2. Apresente uma inspeção inicial com head(), shape, info() e describe().

In [97]:
df2.head()

,date,Consumo_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,Fator_Potencia_Atrasado,Fator_Potencia_Adiantado,WeekStatus,Day_of_week,Load_Type
0,29/04/2018 07:15,2.88,3.82,0.0,60.20,100.00,Weekend,Sunday,Light_Load
1,04/10/2018 12:00,60.77,48.02,0.0,78.46,100.00,Weekday,Thursday,Maximum_Load
2,26/01/2018 11:30,120.42,59.65,0.0,89.61,100.00,Weekday,Friday,Maximum_Load
3,02/06/2018 14:30,3.13,0.00,16.6,100.00,18.53,Weekend,Saturday,Light_Load
4,07/12/2018 15:00,58.86,20.99,0.0,94.19,100.00,Weekday,Friday,Medium_Load

In [98]:
print(f'O dataset possui {df2.shape[0]} linhas e {df2.shape[1]} colunas')

O dataset possui 7008 linhas e 9 colunas

In [99]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7008 entries, 0 to 7007
Data columns (total 9 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   date                                  7008 non-null   object
 1   Consumo_kWh                           7008 non-null   float64
 2   Lagging_Current_Reactive.Power_kVarh  7008 non-null   float64
 3   Leading_Current_Reactive_Power_kVarh  7008 non-null   float64
 4   Fator_Potencia_Atrasado               7008 non-null   float64
 5   Fator_Potencia_Adiantado              7008 non-null   float64
 6   WeekStatus                            7008 non-null   object
 7   Day_of_week                           7008 non-null   object
 8   Load_Type                             7008 non-null   object
dtypes: float64(5), object(4)
memory usage: 492.9+ KB

In [100]:
df2.describe()

,Consumo_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,Fator_Potencia_Atrasado,Fator_Potencia_Adiantado
count,7008.000000,7008.000000,7008.000000,7008.000000,7008.000000
mean,27.790164,13.206839,3.803711,80.672277,84.491448
std,33.717719,16.444246,7.356412,18.869855,30.314798
min,2.450000,0.000000,0.000000,37.870000,12.710000
25%,3.200000,2.380000,0.000000,63.602500,99.710000
50%,4.570000,5.040000,0.000000,87.990000,100.000000
75%,52.107500,22.977500,1.857500,98.842500,100.000000
max,153.140000,87.700000,27.650000,100.000000,100.000000

3. Determine o maior consumo registrado e calcule um limiar de 75% do consumo máximo.

In [101]:
consumoMax_df2 = df2['Consumo_kWh'].max()

limiarConsumo_df2 = consumoMax_df2 * 0.75

consumoMax_df2, limiarConsumo_df2

(153.14, 114.85499999999999)

4. Crie um DataFrame contendo os registros acima desse limiar e calcule a quantidade e o percentual de registros.

In [102]:
df2_altoConsumo = df2[df2['Consumo_kWh'] > limiarConsumo_df2]

nRegistrosAltoConsumo_df2 = len(df2_altoConsumo)
totalRegistros_df2 = len(df2)

percentualAltoConsumo_df2 = (nRegistrosAltoConsumo_df2 / totalRegistros_df2) * 100

print(f"Número de registros com consumo acima do limiar: {nRegistrosAltoConsumo_df2}")
print(f"Total de registros da amostra: {totalRegistros_df2}")
print(f"Percentual de registros com consumo acima do limiar da amostra: {percentualAltoConsumo_df2:.2f}%")

Número de registros com consumo acima do limiar: 129
Total de registros da amostra: 7008
Percentual de registros com consumo acima do limiar da amostra: 1.84%

5. Verifique quantos registros desse DataFrame pertencem à categoria Maximum Load.

In [103]:
df2_altoConsumo['Load_Type'].value_counts()

Load_Type
Maximum_Load    62
Medium_Load     58
Light_Load       9
Name: count, dtype: int64

6. Escolha um dos atributos de fator de potência, observe seus valores e defina um limite coerente para representar valores mais baixos.

In [104]:
df2_altoConsumo['Fator_Potencia_Atrasado'].value_counts()

Fator_Potencia_Atrasado
87.13    2
89.34    2
89.78    2
92.19    2
88.19    2
        ..
92.28    1
89.32    1
92.34    1
93.94    1
92.21    1
Name: count, Length: 124, dtype: int64

In [105]:
limiar_fator_potencia_df2 = 90.0

7. Crie um novo DataFrame contendo simultaneamente consumo elevado e fator de potência abaixo do limite escolhido.

In [106]:
df2_altoConsumo_baixoFatorPotencia = df2_altoConsumo[df2_altoConsumo['Fator_Potencia_Atrasado'] < limiar_fator_potencia_df2]

In [107]:

print(f"Número de registros com consumo elevado e fator de potência abaixo de {limiar_fator_potencia_df2}: {len(df2_altoConsumo_baixoFatorPotencia)}")

df2_altoConsumo_baixoFatorPotencia.head()

Número de registros com consumo elevado e fator de potência abaixo de 90.0: 42

,date,Consumo_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,Fator_Potencia_Atrasado,Fator_Potencia_Adiantado,WeekStatus,Day_of_week,Load_Type
2,26/01/2018 11:30,120.42,59.65,0.0,89.61,100.0,Weekday,Friday,Maximum_Load
295,05/01/2018 11:15,129.85,63.86,0.0,89.74,100.0,Weekday,Friday,Maximum_Load
399,11/09/2018 13:45,122.94,69.26,0.0,87.13,100.0,Weekday,Tuesday,Maximum_Load
605,29/10/2018 16:30,134.60,66.24,0.0,89.72,100.0,Weekday,Monday,Maximum_Load
771,17/11/2018 15:45,132.30,70.06,0.0,88.37,100.0,Weekend,Saturday,Medium_Load

8. Explique por que esse segundo conjunto de registros pode merecer maior atenção da equipe de energia.

Este segundo conjunto de registros, caracterizado por alto consumo e baixo fator de potência, merece maior atenção da equipe de energia, pois um fator de potência baixo indica uso ineficiente da energia elétrica. Isso geralmente leva a:

Maiores perdas de energia: é necessária mais corrente para fornecer a mesma quantidade de potência útil, o que resulta em maiores perdas resistivas no sistema.

Contas de energia mais altas: as concessionárias de energia elétrica costumam cobrar multas por fatores de potência baixos.

Redução da capacidade do sistema: os equipamentos (transformadores, geradores) precisam conduzir mais corrente, reduzindo sua capacidade disponível para a carga útil.

Identificar esses períodos específicos permite que a equipe investigue as causas (por exemplo, equipamentos específicos, padrões operacionais) e implemente medidas corretivas, como dispositivos de correção do fator de potência, que podem melhorar significativamente a eficiência energética e reduzir os custos operacionais.

# **Dataset 3 — Power Consumption of Tetouan City (UCI)**

Fonte: https://archive.ics.uci.edu/dataset/849/power+consumption+of+tetouan+city

Situação:

Uma equipe responsável pelo planejamento da distribuição de energia em Tétouan deseja identificar qual das três zonas apresenta o maior pico de consumo e observar as condições ambientais registradas nos momentos de maior demanda.

1. Renomeie as três variáveis de consumo para Consumo_Zona_1, Consumo_Zona_2 e Consumo_Zona_3.

In [108]:
df3 = pd.read_csv('/content/Tetuan City Power Consumption_SAMPLE_01.csv')
df3.columns

Index(['DateTime', 'Temperature', 'Humidity', 'Wind Speed',
       'Zone 1 Power Consumption', 'Zone 2  Power Consumption',
       'Zone 3  Power Consumption'],
      dtype='object')

In [109]:
df3.rename(columns={'Zone 1 Power Consumption':'Consumo_Zona_1',
                    'Zone 2  Power Consumption':'Consumo_Zona_2',
                    'Zone 3  Power Consumption':'Consumo_Zona_3'}, inplace=True)
df3.head()

,DateTime,Temperature,Humidity,Wind Speed,Consumo_Zona_1,Consumo_Zona_2,Consumo_Zona_3
0,4/18/2017 16:20,22.76,29.73,0.085,32985.14532,19396.7,17623.3
1,12/27/2017 17:10,15.92,54.44,0.085,34737.64259,29803.0,14417.3
2,1/2/2017 11:20,15.08,57.23,0.076,27894.68354,20808.5,16458.8
3,3/19/2017 20:20,12.42,72.30,0.081,42476.93617,23634.1,25089.7
4,4/24/2017 5:50,14.58,80.60,0.080,21341.14101,12006.1,11531.6

2. Determine o consumo máximo registrado em cada uma das três zonas.

In [110]:
consumoMax_df3 = [df3['Consumo_Zona_1'].max(), df3['Consumo_Zona_2'].max(), df3['Consumo_Zona_3'].max()]

3. Identifique qual zona apresenta o maior pico de consumo na amostra.

In [111]:
print(consumoMax_df3)

[51571.49834, 36437.2, 47441.7]

4. Para a zona identificada, calcule 70% do valor máximo e crie um DataFrame com os registros acima desse limiar.

In [112]:
limiarConsumoZona1 = consumoMax_df3[0] * 0.70

df3_altoConsumo = df3[df3['Consumo_Zona_1'] > limiarConsumoZona1]

df3_altoConsumo.head()

,DateTime,Temperature,Humidity,Wind Speed,Consumo_Zona_1,Consumo_Zona_2,Consumo_Zona_3
3,3/19/2017 20:20,12.42,72.30,0.081,42476.93617,23634.1,25089.7
8,12/10/2017 17:50,14.66,65.92,0.075,37286.69202,30716.2,15834.8
12,6/5/2017 23:30,21.03,86.50,0.068,40993.90728,25383.4,24960.0
14,8/23/2017 17:50,27.06,47.58,4.905,37475.16093,24276.2,25140.6
19,6/22/2017 2:40,19.20,65.81,4.924,40676.02649,24754.7,25095.9

5. Conte os registros e calcule o percentual que eles representam.

In [113]:
nRegistrosAltoConsumo_df3 = len(df3_altoConsumo)
totalRegistros_df3 = len(df3)

percentualAltoConsumo_df3 = (nRegistrosAltoConsumo_df3 / totalRegistros_df3) * 100

print(f"Número de registros com consumo acima do limiar: {nRegistrosAltoConsumo_df3}")
print(f"Total de registros da amostra: {totalRegistros_df3}")
print(f"Percentual de registros com consumo acima do limiar da amostra: {percentualAltoConsumo_df3:.2f}%")

Número de registros com consumo acima do limiar: 2388
Total de registros da amostra: 7863
Percentual de registros com consumo acima do limiar da amostra: 30.37%

6. Calcule a temperatura média e crie um segundo DataFrame contendo consumo acima do limiar e temperatura acima da média.

In [114]:
tempMedia = df3['Temperature'].mean()

tempMedia

np.float64(18.78937631947094)

In [115]:
df3_altoConsumo_tempMedia = df3_altoConsumo[df3_altoConsumo['Temperature'] > tempMedia]

len(df3_altoConsumo_tempMedia)

1597

7. Compare os dois conjuntos e explique o que ocorreu com a quantidade de registros após a inclusão da condição ambiental.

A quantidade de registro diminui após a inclusão da condição ambiental.

# **Dataset 4 — Solar Power Generation Data (Kaggle)**

Fonte: https://www.kaggle.com/datasets/anikannal/solar-power-generation-data

Situação:

Uma equipe de operação de uma usina fotovoltaica deseja localizar períodos de alta geração e identificar quais inversores aparecem com maior frequência nesses momentos. Nesta atividade, o foco inicial será o arquivo de geração da planta, sem realizar junção com o arquivo de sensores.

1. Carregue a amostra e renomeie as principais variáveis para nomes mais claros, como Potencia_CC, Potencia_CA e Geracao_Diaria.

In [116]:
df4 = pd.read_csv('/content/Plant_1_Generation_Data_SAMPLE_01.csv')

df4.columns

Index(['DATE_TIME', 'SOURCE_KEY', 'DC_POWER', 'AC_POWER', 'DAILY_YIELD',
       'TOTAL_YIELD'],
      dtype='object')

In [117]:
df4.rename(columns={'DATE_TIME':'DATA_HORA',
                    'DC_POWER':'POTENCIA_CC',
                    'AC_POWER':'POTENCIA_CA',
                    'DAILY_YIELD':'GERACAO_DIARIA',
                    'TOTAL_YIELD':'GERACAO_TOTAL'}, inplace=True)

2. Apresente head(), shape, info() e describe().

In [118]:
df4.head()

,DATA_HORA,SOURCE_KEY,POTENCIA_CC,POTENCIA_CA,GERACAO_DIARIA,GERACAO_TOTAL
0,10-06-2020 19:00,uHbuxQJl8lW7ozc,0.00,0.000,6645.000,7240508.000
1,28-05-2020 00:15,rGa61gmuvPhdLxV,0.00,0.000,0.000,7206549.000
2,17-05-2020 15:15,sjndEbLyjtCKgGv,7333.88,718.062,6442.000,7036055.000
3,01-06-2020 04:15,ih0vzX44oOqAx2f,0.00,0.000,0.000,6308232.000
4,17-05-2020 09:00,z9Y9gH1T5YWrNuG,7665.50,750.438,961.375,7021701.375

In [119]:
print(f'O dataset possui {df4.shape[0]} linhas e {df4.shape[1]} colunas')

O dataset possui 13756 linhas e 6 colunas

In [120]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13756 entries, 0 to 13755
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   DATA_HORA       13756 non-null  object
 1   SOURCE_KEY      13756 non-null  object
 2   POTENCIA_CC     13756 non-null  float64
 3   POTENCIA_CA     13756 non-null  float64
 4   GERACAO_DIARIA  13756 non-null  float64
 5   GERACAO_TOTAL   13756 non-null  float64
dtypes: float64(4), object(2)
memory usage: 644.9+ KB

In [121]:
df4.describe()

        POTENCIA_CC   POTENCIA_CA  GERACAO_DIARIA  GERACAO_TOTAL
count  13756.000000  13756.000000    13756.000000   1.375600e+04
mean    3135.848662    306.695495     3319.235216   6.978829e+06
std     4023.069619    393.124284     3142.249927   4.162164e+05
min        0.000000      0.000000        0.000000   6.183645e+06
25%        0.000000      0.000000        0.000000   6.509779e+06
50%      370.071500     35.771400     2730.425000   7.146218e+06
75%     6350.562500    622.065500     6293.782500   7.267996e+06
max    14416.100000   1405.590000     9163.000000   7.846821e+06

3. Determine a maior potência CA registrada.

In [122]:
maxPotenciaCA = df4['POTENCIA_CA'].max()

maxPotenciaCA

1405.59

4. Calcule um limiar correspondente a 70% da potência CA máxima.

In [123]:
limiarPotenciaCA = maxPotenciaCA * 0.70

limiarPotenciaCA

983.9129999999999

5. Crie um DataFrame contendo somente registros acima desse limite e calcule sua quantidade e percentual.

In [124]:
df4_potenciaCA = df4[df4['POTENCIA_CA'] > limiarPotenciaCA]

df4_potenciaCA.head()

,DATA_HORA,SOURCE_KEY,POTENCIA_CC,POTENCIA_CA,GERACAO_DIARIA,GERACAO_TOTAL
11,26-05-2020 12:15,bvBOhCH3iADSZry,11830.1,1153.83,4028.14,6396364.143
46,15-06-2020 14:30,wCURE6d3bPkepu2,10571.3,1032.07,5366.57,7015064.571
48,25-05-2020 10:15,z9Y9gH1T5YWrNuG,11050.1,1079.86,2174.29,7082812.286
72,13-06-2020 11:30,7JYdWkrLSPkdwr4,11094.5,1082.44,3570.25,7815987.250
76,07-06-2020 13:00,VHMLBKoKgIrUVDU,12663.4,1234.69,4976.71,7382965.714

In [125]:
nRegistrosPotenciaCA_df4 = len(df4_potenciaCA)

totalRegistros_df4 = len(df4)

percentualAltoConsumo_df4 = (nRegistrosPotenciaCA_df4 / totalRegistros_df4) * 100

print(f"Número de registros com potência acima do limiar: {nRegistrosPotenciaCA_df4}")
print(f"Total de registros da amostra: {totalRegistros_df4}")
print(f"Percentual de registros com potência acima do limiar:da amostra: {percentualAltoConsumo_df4:.2f}%")

Número de registros com potência acima do limiar: 1185
Total de registros da amostra: 13756
Percentual de registros com potência acima do limiar:da amostra: 8.61%

6. Utilize value_counts() em SOURCE_KEY dentro do DataFrame de alta geração.

In [126]:
df4['SOURCE_KEY'].value_counts()

SOURCE_KEY
z9Y9gH1T5YWrNuG    672
WRmjgnKYAwPKWDb    651
ih0vzX44oOqAx2f    638
1IF53ai7Xc0U56Y    635
wCURE6d3bPkepu2    635
McdE0feGgRqW7Ca    635
ZoEaEvLYb1n2sOq    633
VHMLBKoKgIrUVDU    631
YxYtjZvoooNbGkE    631
1BY6WEcLGh8j5v7    630
adLQvlD726eNBSB    629
7JYdWkrLSPkdwr4    627
zBIq5rxdHJRwDNY    623
3PZuoBAID5Wc2HD    623
ZnxXDlPa8U1GXgE    617
rGa61gmuvPhdLxV    616
uHbuxQJl8lW7ozc    612
zVJPv84UY57bAof    611
bvBOhCH3iADSZry    609
pkci93gMrogZuBj    603
iCRJl6heRkivqQ3    601
sjndEbLyjtCKgGv    594
Name: count, dtype: int64

In [127]:
inversor_alta_geracao = df4_potenciaCA['SOURCE_KEY'].value_counts()
display(inversor_alta_geracao)

SOURCE_KEY
adLQvlD726eNBSB    68
McdE0feGgRqW7Ca    65
ZnxXDlPa8U1GXgE    63
pkci93gMrogZuBj    62
ZoEaEvLYb1n2sOq    61
1IF53ai7Xc0U56Y    59
YxYtjZvoooNbGkE    58
sjndEbLyjtCKgGv    57
z9Y9gH1T5YWrNuG    56
uHbuxQJl8lW7ozc    55
zVJPv84UY57bAof    54
zBIq5rxdHJRwDNY    53
ih0vzX44oOqAx2f    53
WRmjgnKYAwPKWDb    52
3PZuoBAID5Wc2HD    51
iCRJl6heRkivqQ3    51
VHMLBKoKgIrUVDU    51
wCURE6d3bPkepu2    49
rGa61gmuvPhdLxV    43
7JYdWkrLSPkdwr4    43
1BY6WEcLGh8j5v7    42
bvBOhCH3iADSZry    39
Name: count, dtype: int64

7. Identifique qual inversor aparece com maior frequência nos registros de alta geração e descreva o que esse resultado permite observar, sem concluir desempenho ou falha apenas com esse recorte.

O inversor `z9Y9gH1T5YWrNuG` é o que aparece com maior frequência nos registros de alta geração de potência CA. Isso significa que, nos momentos em que a usina está produzindo sua maior potência (acima de 70% do máximo), este inversor em particular está frequentemente ativo e contribuindo significativamente para essa produção. É uma observação de padrão de operação, não indicando necessariamente um melhor desempenho ou falha sem uma análise mais aprofundada dos dados de todos os inversores e seus respectivos tempos de operação.

# **Dataset 5 — Wind & Solar Energy Production (Kaggle)**

Fonte: https://www.kaggle.com/datasets/ahmeduzaki/wind-and-solar-energy-production-dataset

Situação:

Um operador de um portfólio de fontes renováveis deseja comparar a ocorrência de períodos de alta produção solar e alta produção eólica. Como as duas fontes possuem escalas próprias, cada uma deverá ser comparada com o seu próprio valor máximo.

1. Renomeie as variáveis principais para Geracao_Solar e Geracao_Eolica.

In [128]:
df5 = pd.read_csv('/content/Energy Production Dataset_SAMPLE_01.csv')

df5['Source'].unique()

array(['Wind', 'Solar'], dtype=object)

In [129]:
df5['Source'] = df5["Source"].replace({
    "Wind": "Geracao_Eolica",
    "Solar": "Geracao_Solar"
})

df5.head()

         Date  Start_Hour  End_Hour          Source  Production
0  12/18/2022          21        22  Geracao_Eolica       11400
1   1/29/2024          14        15  Geracao_Eolica        7917
2    8/1/2024          15        16   Geracao_Solar        8835
3  11/10/2020           1         2  Geracao_Eolica         989
4  12/19/2022           1         2  Geracao_Eolica       12526

2. Determine o valor máximo registrado para cada fonte.

In [130]:
df5gs = df5[df5['Source'] == 'Geracao_Solar']

df5ge = df5[df5['Source'] == 'Geracao_Eolica']

df5gs.head()

          Date  Start_Hour  End_Hour         Source  Production
2     8/1/2024          15        16  Geracao_Solar        8835
5   10/18/2024          13        14  Geracao_Solar        4855
6    4/10/2020          17        18  Geracao_Solar        3692
13    6/2/2021          15        16  Geracao_Solar        5561
16    5/2/2021          13        14  Geracao_Solar        4993

In [131]:
df5ge.head()

         Date  Start_Hour  End_Hour          Source  Production
0  12/18/2022          21        22  Geracao_Eolica       11400
1   1/29/2024          14        15  Geracao_Eolica        7917
3  11/10/2020           1         2  Geracao_Eolica         989
4  12/19/2022           1         2  Geracao_Eolica       12526
7   1/25/2023           0         1  Geracao_Eolica        2156

In [132]:
maxSolar = df5gs['Production'].max()

maxSolar

16316

In [133]:
maxEolica = df5ge['Production'].max()

maxEolica

22929

3. Calcule separadamente 70% do máximo solar e 70% do máximo eólico.

In [134]:
limiarSolar = maxSolar * 0.70

limiarSolar

11421.199999999999

In [135]:
limiarEolica = maxEolica * 0.70

limiarEolica

16050.3

4. Crie um DataFrame para registros de alta geração solar e outro para registros de alta geração eólica.

In [136]:
altaGeracaoSolar_df5 = df5gs[df5gs['Production'] > limiarSolar]

altaGeracaoSolar_df5.head()

          Date  Start_Hour  End_Hour         Source  Production
77    7/8/2025          13        14  Geracao_Solar       13125
178  3/19/2025          13        14  Geracao_Solar       13786
183  8/17/2025          12        13  Geracao_Solar       11455
187  7/16/2025          12        13  Geracao_Solar       16160
207  3/31/2025          12        13  Geracao_Solar       12441

In [137]:
altaGeracaoEolica_df5 = df5ge[df5ge['Production'] > limiarEolica]

altaGeracaoEolica_df5.head()

           Date  Start_Hour  End_Hour          Source  Production
20     1/3/2024           0         1  Geracao_Eolica       17272
32    3/11/2021          13        14  Geracao_Eolica       16144
103   1/29/2025           0         1  Geracao_Eolica       18199
151   12/8/2024           6         7  Geracao_Eolica       16946
192  11/19/2024           2         3  Geracao_Eolica       16568

5. Conte os registros de cada DataFrame e calcule seus respectivos percentuais.

In [138]:
totalRegistros_df5 = len(df5)

totalRegistrosSolar_df5 = len(df5gs)
totalRegistrosEolica_df5 = len(df5ge)

percentualGeracaoSolar = (totalRegistrosSolar_df5 / totalRegistros_df5) * 100
percentualGeracaoEolica = (totalRegistrosEolica_df5 / totalRegistros_df5) * 100

nRegistrosAltaGeracaoSolar_df5 = len(altaGeracaoSolar_df5)
nRegistrosAltaGeracaoEolica_df5 = len(altaGeracaoEolica_df5)

percentualAltaGeracaoSolar_df5 = (nRegistrosAltaGeracaoSolar_df5 / totalRegistrosSolar_df5) * 100
percentualAltaGeracaoEolica_df5 = (nRegistrosAltaGeracaoEolica_df5 / totalRegistrosEolica_df5) * 100

print(f"Total de registros da amostra: {totalRegistros_df5}")
print(f"Total de registros de geração solar da amostra: {totalRegistrosSolar_df5}")
print(f"Total de registros de geração eolica da amostra: {totalRegistrosEolica_df5}")

print(f"\nPercentual de registros de geracao solar da amostra: {percentualGeracaoSolar:.2f}%")
print(f"Percentual de registros de geracao eolica da amostra: {percentualGeracaoEolica:.2f}%")

print(f"\nNúmero de registros com geracao solar acima do limiar: {nRegistrosAltaGeracaoSolar_df5}")
print(f"Número de registros com geracao eolica acima do limiar: {nRegistrosAltaGeracaoEolica_df5}")

print(f"\nPercentual de registros de geracao solar acima do limiar: {percentualAltaGeracaoSolar_df5:.2f}%")
print(f"Percentual de registros de geracao eolica acima do limiar: {percentualAltaGeracaoEolica_df5:.2f}%")

Total de registros da amostra: 10373
Total de registros de geração solar da amostra: 1846
Total de registros de geração eolica da amostra: 8527

Percentual de registros de geracao solar da amostra: 17.80%
Percentual de registros de geracao eolica da amostra: 82.20%

Número de registros com geracao solar acima do limiar: 45
Número de registros com geracao eolica acima do limiar: 245

Percentual de registros de geracao solar acima do limiar: 2.44%
Percentual de registros de geracao eolica acima do limiar: 2.87%

6. Compare qual fonte aparece com maior frequência acima de 70% do seu próprio máximo.

In [139]:
nRegistrosAltaGeracaoSolar_df5, nRegistrosAltaGeracaoEolica_df5

(45, 245)

A geração eolica tem mais registros acima do limiar

7. Explique por que não seria adequado utilizar diretamente o mesmo valor numérico de potência como limite para as duas fontes sem antes observar a escala de cada variável.

Porque cada fonte tem um intervalo de geração diferente.

# **Dataset 6 — Individual Household Electric Power Consumption (UCI)**

Fonte: https://archive.ics.uci.edu/dataset/235/individual+household+electric+power+consumption

Situação:

Uma residência possui monitoramento elétrico detalhado e deseja identificar episódios de demanda elevada que também apresentem corrente acima do comportamento médio. O dataset é o mesmo utilizado como referência em aula, mas o critério de análise será diferente.

1. Carregue a nova amostra e organize os atributos utilizando nomes mais simples.

In [140]:
df6 = pd.read_csv('/content/household_power_consumption_SAMPLE_01.csv')

df6.columns

Index(['Date', 'Global_active_power', 'Global_reactive_power', 'Voltage',
       'Global_intensity', 'Sub_metering_1', 'Sub_metering_2',
       'Sub_metering_3'],
      dtype='object')

In [141]:
df6.rename(columns={'Date':'Data',
                    'Global_active_power':'Potencia_Ativa',
                    'Global_reactive_power':'Potencia_Reativa',
                    'Voltage':'Voltagem',
                    'Global_intensity':'Corrente',
                    'Sub_metering_1':'Sub_Medicao_1',
                    'Sub_metering_1':'Sub_Medicao_2',
                    'Sub_metering_1':'Sub_Medicao_3'}, inplace=True)

2. Determine o valor máximo de potência ativa.

In [142]:
maxPA = df6['Potencia_Ativa'].max()

maxPA

10.536

3. Calcule 75% do valor máximo e crie um DataFrame contendo registros acima desse limite.

In [143]:
limiarPA = maxPA * 0.75

limiarPA

7.901999999999999

In [144]:
potenciaAtiva_df6 = df6[df6['Potencia_Ativa'] > limiarPA]

potenciaAtiva_df6.head()

,Data,Potencia_Ativa,Potencia_Reativa,Voltagem,Corrente,Sub_Medicao_3,Sub_metering_2,Sub_metering_3
3132,24/1/2009,8.540,0.238,236.23,36.0,80.0,35.0,17.0
3630,9/1/2007,8.278,0.088,231.50,35.6,0.0,71.0,17.0
10339,4/11/2010,8.026,0.066,236.45,33.8,37.0,73.0,18.0
11695,5/4/2007,8.102,0.190,229.31,35.4,35.0,35.0,17.0
27983,19/10/2008,10.290,0.302,230.90,44.6,35.0,66.0,17.0

4. Calcule a quantidade e o percentual de registros selecionados.

In [145]:
totalRegistros_df6 = len(df6)

nRegistrosPA = len(potenciaAtiva_df6)

percentualPA_df6 = (nRegistrosPA / totalRegistros_df6) * 100

print(f"Número de registros com consumo acima do limiar: {nRegistrosPA}")
print(f"Total de registros da amostra: {totalRegistros_df6}")
print(f"Percentual da amostra que representa: {percentualPA_df6:.2f}%")

Número de registros com consumo acima do limiar: 58
Total de registros da amostra: 204928
Percentual da amostra que representa: 0.03%

5. Calcule a corrente média da amostra.

In [146]:
correnteMedia = df6['Corrente'].mean()

correnteMedia

np.float64(4.6344296533416625)

6. Crie um segundo DataFrame contendo simultaneamente potência ativa acima de 75% do máximo e corrente acima da média.

In [147]:
potenciaAtiva_correnteMedia_df6 = potenciaAtiva_df6[potenciaAtiva_df6['Corrente'] > correnteMedia]

len(potenciaAtiva_correnteMedia_df6)

58

7. Compare os dois conjuntos e explique o efeito da inclusão da corrente como segunda condição.

In [148]:
print(f'O DataFrame potenciaAtiva_df6 possui {len(potenciaAtiva_df6)} registros.')
print(f'O DataFrame potenciaAtiva_correnteMedia_df6 possui {len(potenciaAtiva_correnteMedia_df6)} registros.')

O DataFrame potenciaAtiva_df6 possui 58 registros.
O DataFrame potenciaAtiva_correnteMedia_df6 possui 58 registros.

Ao incluir a condição de `Corrente` acima da média da amostra, o número de registros no DataFrame `potenciaAtiva_correnteMedia_df6` pode diminuir em relação a `potenciaAtiva_df6`. No entanto, como no resultado anterior ambos os DataFrames tiveram o mesmo número de registros (58), isso indica que todos os registros com `Potencia_Ativa` acima de 75% do máximo também possuem `Corrente` acima da média da amostra. Em outras palavras, para este recorte de dados, alta potência ativa está sempre associada a uma corrente acima da média. Isso pode sugerir que a `Corrente` é um fator diretamente proporcional à `Potencia_Ativa` nestes cenários de alta demanda, e que a condição de 'corrente acima da média' não impôs uma restrição adicional que eliminasse registros do conjunto de alta potência ativa.